# -*- coding: utf-8 -*-
"""7 gunluk sinav calisma plani — sifirdan baslayanlar icin."""

STUDY_PLAN = [
    {
        "day": 1,
        "title": "Rails nedir? Temel iskelet",
        "time": "2-3 saat",
        "goal": "MVC ve Ruby mantigini anla. Kod yazmana gerek yok.",
        "tasks": [
            {"text": "Hafta 2 — Basit Anlatim kutusunu oku", "link": "#hafta-2-ruby-rails-giris"},
            {"text": "MVC akisini ezberle: routes → controller → model → view", "link": "#hafta-2-ruby-rails-giris"},
            {"text": "Ruby Temelleri panelini ac (Integer, String, Symbol farki)", "link": "#hafta-2-ruby-rails-giris"},
            {"text": "Rails Dizin Yapisini gozden gecir (app/, config/, db/)", "link": "#hafta-2-ruby-rails-giris"},
            {"text": "Test: Hafta 2 sorulari (1-5) — cevaplari kontrol et", "link": "#sinav-sorulari-kendini-test-et"},
        ],
        "remember": [
            "Ruby'de her sey nesnedir",
            "Symbol tekil, String her seferinde yeni nesne",
            "? metot → true/false, ! metot → orijinali degistirir",
        ],
    },
    {
        "day": 2,
        "title": "Veritabani & Active Record",
        "time": "2-3 saat",
        "goal": "ORM ve find/find_by/where farkini bil.",
        "tasks": [
            {"text": "Hafta 3 — Basit Anlatim oku", "link": "#hafta-3-orm-active-record"},
            {"text": "ORM = tablo ↔ Ruby sinifi mantigini anla", "link": "#hafta-3-orm-active-record"},
            {"text": "find vs find_by vs where tablosunu ezberle", "link": "#hafta-3-orm-active-record"},
            {"text": "Migration panelini oku (db:migrate, db:rollback)", "link": "#hafta-3-orm-active-record"},
            {"text": "Komutlar bolumunden db:* komutlarina bak", "link": "#komut-hizli-referans"},
            {"text": "Test: Hafta 3 sorulari (6-10)", "link": "#sinav-sorulari-kendini-test-et"},
        ],
        "remember": [
            "find(1) → bulamazsa HATA",
            "find_by → bulamazsa nil",
            "where → liste doner",
            "db:reset = sil + yeniden kur + seed",
        ],
    },
    {
        "day": 3,
        "title": "Routes, HTTP & CRUD",
        "time": "2-3 saat",
        "goal": "HTTP metotlari ve 7 CRUD route'u bil.",
        "tasks": [
            {"text": "Hafta 4 — Basit Anlatim oku", "link": "#hafta-4-enum-routes-controllers"},
            {"text": "GET/POST/PUT/PATCH/DELETE ne zaman kullanilir ezberle", "link": "#hafta-4-enum-routes-controllers"},
            {"text": "resources :posts = 7 route (index,show,new,create,edit,update,destroy)", "link": "#hafta-4-enum-routes-controllers"},
            {"text": "Enum panelini oku (draft: 0 ne demek?)", "link": "#hafta-4-enum-routes-controllers"},
            {"text": "posts_path vs posts_url farkini ogren", "link": "#hafta-4-enum-routes-controllers"},
            {"text": "Test: Hafta 4 sorulari (11-15)", "link": "#sinav-sorulari-kendini-test-et"},
        ],
        "remember": [
            "GET = oku, POST = olustur, DELETE = sil",
            "Enum: DB'de sayi, kodda isim (draft: 0)",
            "_path = goreceli yol, _url = tam URL",
        ],
    },
    {
        "day": 4,
        "title": "Formlar & Guvenlik",
        "time": "2 saat",
        "goal": "Strong Parameters ve form mantigini anla.",
        "tasks": [
            {"text": "Hafta 5 — Basit Anlatim oku", "link": "#hafta-5-form-helpers-strong-parameters"},
            {"text": "form_with model: @post ne ise yarar?", "link": "#hafta-5-form-helpers-strong-parameters"},
            {"text": "Strong Parameters panelini oku (post_params)", "link": "#hafta-5-form-helpers-strong-parameters"},
            {"text": "authenticity_token = CSRF korumasi", "link": "#hafta-5-form-helpers-strong-parameters"},
            {"text": "Partial (_form) ve before_action mantigi", "link": "#hafta-5-form-helpers-strong-parameters"},
            {"text": "Test: Hafta 5 sorulari (16-20)", "link": "#sinav-sorulari-kendini-test-et"},
        ],
        "remember": [
            "Strong Params → mass assignment saldirisini onler",
            "Partial dosya adi _ ile baslar",
            "button_to DELETE icin form olusturur",
        ],
    },
    {
        "day": 5,
        "title": "Bootstrap & Model Iliskileri",
        "time": "2-3 saat",
        "goal": "Grid sistemi ve tablo iliskilerini bil.",
        "tasks": [
            {"text": "Hafta 6 — Basit Anlatim (12 sutun grid, container)", "link": "#hafta-6-bootstrap-frontend"},
            {"text": "Hafta 7 — Basit Anlatim (belongs_to, has_many, HABTM)", "link": "#hafta-7-model-iliskileri-kategori"},
            {"text": "belongs_to FK hangi tabloda? — ezberle", "link": "#hafta-7-model-iliskileri-kategori"},
            {"text": "HABTM join table: id yok, iki FK var", "link": "#hafta-7-model-iliskileri-kategori"},
            {"text": "Test: Hafta 6 sorulari (21-23) + Hafta 7 (24-27)", "link": "#sinav-sorulari-kendini-test-et"},
        ],
        "remember": [
            "Bootstrap grid = 12 sutun",
            "col-md-8: 768px+ yan yana, mobilde alt alta",
            "dependent: :destroy → ust silinince alt da silinir",
        ],
    },
    {
        "day": 6,
        "title": "Validation, I18n & Devise",
        "time": "2-3 saat",
        "goal": "Dogrulama, coklu dil ve kullanici girisi konularini bitir.",
        "tasks": [
            {"text": "Hafta 8 — validation vs normalization farki", "link": "#hafta-8-validation-active-storage"},
            {"text": "presence, uniqueness, length ne kontrol eder?", "link": "#hafta-8-validation-active-storage"},
            {"text": "HTTP 422 = validasyon hatasi", "link": "#hafta-8-validation-active-storage"},
            {"text": "Hafta 9 — I18n.t, FriendlyId, Action Text (kisa oku)", "link": "#hafta-9-i18n-friendlyid-action-text"},
            {"text": "Hafta 10 — Devise, Authentication vs Authorization", "link": "#hafta-10-devise-authorization"},
            {"text": "Test: Hafta 8-10 sorulari (28-39)", "link": "#sinav-sorulari-kendini-test-et"},
        ],
        "remember": [
            "Validation reddeder, normalization duzenler",
            "Authentication = kimlik, Authorization = yetki",
            "authenticate_user! → giris zorunlu",
        ],
    },
    {
        "day": 7,
        "title": "Tekrar & Sinav Gunu",
        "time": "3-4 saat",
        "goal": "Tum test sorularini 2. kez coz. Ezber listesini tekrar et.",
        "tasks": [
            {"text": "15 maddelik SINAV EZBER listesini oku (asagida)", "link": "#sinav-ezber-listesi"},
            {"text": "39 test sorusunun TAMAMINI 2. tur coz", "link": "#sinav-sorulari-kendini-test-et"},
            {"text": "Yanlis yaptigin haftalari tekrar oku", "link": "#7-gunluk-plan"},
            {"text": "Komutlar bolumunu son kez gozden gecir", "link": "#komut-hizli-referans"},
            {"text": "MVC + HTTP + find/find_by/where tekrar et", "link": "#sinav-ezber-listesi"},
        ],
        "remember": [
            "Sakin ol — cogu soru kavram sorusu",
            "Bilmediginde mantik yurut: MVC akisina bak",
            "Enum, Strong Params, Devise en cok cikan konular",
        ],
    },
]

MUST_KNOW = [
    ("Ruby'de her sey nesnedir", "3.class → Integer → Numeric → Object"),
    ("MVC akisi", "routes.rb → Controller → Model → View → HTML"),
    ("ORM", "Veritabani tablosu = Ruby model sinifi"),
    ("find(1)", "Bulamazsa exception (hata) firlatir"),
    ("find_by(...)", "Bulamazsa nil doner"),
    ("where(...)", "Filtreler, liste (Relation) doner"),
    ("resources :posts", "7 CRUD route otomatik olusturur"),
    ("GET / POST / DELETE", "Oku / Olustur / Sil"),
    ("Enum draft: 0", "DB'de 0, kodda draft anlamina gelir"),
    ("Strong Parameters", "Sadece izin verilen alanlar gecer (guvenlik)"),
    ("Partial _form", "Dosya adi _ ile baslar, tekrar kullanilir"),
    ("Bootstrap grid", "12 sutun; col-md-6 = yarim genislik"),
    ("belongs_to", "Foreign key bu tabloda bulunur"),
    ("Validation vs Normalization", "Validation reddeder, normalization duzenler"),
    ("Authentication vs Authorization", "Kimlik dogrulama vs yetki kontrolu"),
]
