# -*- coding: utf-8 -*-
"""Konu indeksi terimleri — bilgi kutusu (tooltip) icerikleri."""

OOP_GLOSSARY = {
    "Prosedürel vs OOP": {
        "title": "Prosedurel vs OOP",
        "what": "Prosedurel: veri + fonksiyonlar ayri. OOP: veri ve davranis nesne icinde birlesir.",
        "how": "Prosedurel: toplam(a,b). OOP: hesap.topla() — islem nesnenin uzerinde yapilir.",
        "code": "class Hesap:\n    def topla(self, a, b):\n        return a + b",
    },
    "Sınıf & Nesne": {
        "title": "Sinif ve Nesne",
        "what": "Sinif = kalip (tarif). Nesne = o kaliptan uretilen gercek ornek.",
        "how": "class Ogrenci tanimla, o = Ogrenci('Ali') ile nesne olustur.",
        "code": "class Ogrenci:\n    pass\n\nali = Ogrenci()",
    },
    "Kapsülleme": {
        "title": "Kapsulleme",
        "what": "Nesnenin ic verisini gizler; disaridan sadece izin verilen yollarla erisilir.",
        "how": "Python: _veri veya __veri. Ruby: @veri + attr_reader.",
        "code": "class Hesap:\n    def __init__(self):\n        self.__bakiye = 0",
    },
    "Kalıtım": {
        "title": "Kalitim (Miras)",
        "what": "Alt sinif ust sinifin ozelliklerini ve metotlarini otomatik alir.",
        "how": "class Cocuk(Ebeveyn): — IS-A iliskisi.",
        "code": "class Hayvan: pass\nclass Kopek(Hayvan): pass",
    },
    "super()": {
        "title": "super()",
        "what": "Ust sinifin ayni isimli metodunu veya __init__ metodunu cagirir.",
        "how": "Alt sinifta override ederken once ust davranisi calistirmak icin kullan.",
        "code": "class Cocuk(Ebeveyn):\n    def __init__(self, ad):\n        super().__init__(ad)",
    },
    "Çoklu miras & MRO": {
        "title": "Coklu miras ve MRO",
        "what": "Birden fazla ust sinif. MRO metot arama sirasini belirler.",
        "how": "class C(A, B): — C.__mro__ ile sirayi gor.",
        "code": "class A: pass\nclass B: pass\nclass C(A, B): pass",
    },
    "@staticmethod": {
        "title": "@staticmethod",
        "what": "Nesneye bagli olmayan; self almayan yardimci metot.",
        "how": "Sinif adiyla cagrilir: Matematik.topla(1, 2).",
        "code": "@staticmethod\n    def topla(a, b):\n        return a + b",
    },
    "Polimorfizm": {
        "title": "Polimorfizm",
        "what": "Ayni metot adi farkli siniflarda farkli davranis gosterir.",
        "how": "Override ile ust metot yeniden yazilir.",
        "code": "def ses(h):\n    print(h.speak())",
    },
    "Soyut sınıf (ABC)": {
        "title": "Soyut sinif (ABC)",
        "what": "Dogrudan nesne uretilemeyen sablon sinif.",
        "how": "from abc import ABC. Alt sinif tum soyut metotlari yazmali.",
        "code": "class Sekil(ABC):\n    @abstractmethod\n    def alan(self): pass",
    },
    "@abstractmethod": {
        "title": "@abstractmethod",
        "what": "Alt sinifin MUTLAKA yazmasi gereken metodu isaretler.",
        "how": "Soyut sinifta tanimla, alt sinifta gercek kodu yaz.",
        "code": "@abstractmethod\n    def hesapla(self):\n        pass",
    },
    "Tasarım desenleri": {
        "title": "Tasarim desenleri",
        "what": "Tekrar eden tasarim problemlerine kanitlanmis cozum sablonlari.",
        "how": "Singleton, Factory, Observer en sik ornekler.",
        "code": "# Singleton, Factory, Observer...",
    },
    "SOLID": {
        "title": "SOLID",
        "what": "Bes tasarim ilkesi: S, O, L, I, D.",
        "how": "Sinavda tanim + kotu/iyi kod beklenir.",
        "code": "# SRP OCP LSP ISP DIP",
    },
    "SRP": {
        "title": "SRP — Tek Sorumluluk",
        "what": "Bir sinif yalnizca tek bir degisim nedeni olmali.",
        "how": "Her sinif tek is yapar.",
        "code": "# MakyajHizmeti, FinansYonetimi ayri",
    },
    "OCP": {
        "title": "OCP — Acik/Kapali",
        "what": "Genislemeye acik, degisiklige kapali.",
        "how": "Yeni tip icin yeni sinif ekle, if/elif degistirme.",
        "code": "class Daire(AlanHesaplayici): ...",
    },
    "LSP": {
        "title": "LSP — Liskov",
        "what": "Alt sinif ust sinifin yerine konulunca program bozulmamali.",
        "how": "Dosya.read() her zaman str donmeli.",
        "code": "def oku(f: Dosya):\n    return f.read()",
    },
    "ISP": {
        "title": "ISP — Arayuz Ayirimi",
        "what": "Kullanilmayan metotlari implement etmek zorunda kalma.",
        "how": "Eatable, Flyable gibi kucuk arayuzler.",
        "code": "class Kedi(Eatable): ...",
    },
    "DIP": {
        "title": "DIP — Bagimlilik Tersine Cevirme",
        "what": "Somut sinif yerine soyutlamaya bagimli ol.",
        "how": "NotificationManager → Sender arayuzu.",
        "code": "def __init__(self, sender: Sender): ...",
    },
}

INTPROG_GLOSSARY = {
    "Active Record": {"title": "Active Record", "what": "Rails ORM; tablo = model.", "how": "Post.create, Post.all", "code": "class Post < ApplicationRecord\nend"},
    "ORM": {"title": "ORM", "what": "Tablo ↔ Ruby sinifi eslemesi.", "how": "SQL yazmadan CRUD.", "code": "Post.all"},
    "Migration": {"title": "Migration", "what": "DB semasini versiyonlu degistirir.", "how": "rails db:migrate", "code": "add_column :posts, :status, :integer"},
    "attr_accessor / reader / writer": {
        "title": "attr_accessor / reader / writer",
        "what": "Instance variable (@) icin otomatik erisim metotlari uretir.",
        "how": "reader=oku, writer=yaz, accessor=ikisi. Kapsulleme icin kullan.",
        "code": "class User\n  attr_accessor :name\nend\nu = User.new\nu.name = 'Ali'",
    },
    "attr_accessor": {"title": "attr_accessor", "what": "Getter + setter otomatik.", "how": "attr_reader, attr_writer, attr_accessor", "code": "attr_accessor :name"},
    "Enum": {"title": "Enum", "what": "Integer'a isim baglar.", "how": "enum status: { draft: 0 }", "code": "post.draft?"},
    "belongs_to": {"title": "belongs_to", "what": "FK bu tabloda.", "how": "belongs_to :category", "code": "belongs_to :user"},
    "has_many": {"title": "has_many", "what": "Karsi tarafta cok kayit.", "how": "has_many :posts", "code": "category.posts"},
    "HABTM": {"title": "HABTM", "what": "Coktan coga join tablo.", "how": "has_and_belongs_to_many", "code": "has_and_belongs_to_many :tags"},
    "Strong Parameters": {"title": "Strong Parameters", "what": "Izinli params alanlari.", "how": "require().permit()", "code": "params.require(:post).permit(:title)"},
    "Devise": {"title": "Devise", "what": "Authentication gem.", "how": "authenticate_user! ve current_user", "code": "devise_for :users"},
    "Authentication": {"title": "Authentication", "what": "Kimlik dogrulama.", "how": "Devise sign_in", "code": "user_signed_in?"},
    "Authorization": {"title": "Authorization", "what": "Yetkilendirme.", "how": "admin? rol kontrolu", "code": "current_user.admin?"},
    "ERB": {"title": "ERB", "what": "View'da Ruby.", "how": "<% %> kod, <%= %> cikti", "code": "<%= @post.title %>"},
    "resources": {"title": "resources", "what": "7 REST route.", "how": "resources :posts", "code": "resources :posts"},
    "CRUD": {"title": "CRUD", "what": "Create Read Update Delete.", "how": "HTTP metotlari ile", "code": "GET POST PATCH DELETE"},
    "find": {"title": "find", "what": "ID ile arar; yoksa hata.", "how": "Post.find(1)", "code": "Post.find(params[:id])"},
    "find_by": {"title": "find_by", "what": "Kosul; yoksa nil.", "how": "Post.find_by(title: 'x')", "code": "Post.find_by(slug: s)"},
    "where": {"title": "where", "what": "Filtre; Relation doner.", "how": "Post.where(status: 1)", "code": "Post.where(active: true)"},
    "validates": {"title": "validates", "what": "Model dogrulama.", "how": "presence, uniqueness, length", "code": "validates :title, presence: true"},
    "I18n": {"title": "I18n", "what": "Coklu dil.", "how": "t() ve locales/*.yml", "code": "t('posts.title')"},
    "Bloklar": {"title": "Bloklar", "what": "do/end veya { } ile kod blogu.", "how": "each, map, yield", "code": "[1,2].each { |n| puts n }"},
    "MVC": {"title": "MVC", "what": "Model View Controller.", "how": "Routes → Controller → Model → View", "code": "@post = Post.find(1)"},
    "Symbol": {"title": "Symbol", "what": ":name tekil nesne.", "how": "Hash key'lerde :draft", "code": "{ status: :published }"},
    "Polimorfizm": {"title": "Polimorfizm", "what": "Ayni metot farkli davranis.", "how": "Override in Ruby", "code": "def speak; 'Hav'; end"},
    "Kalıtım": {"title": "Kalitim", "what": "class Child < Parent", "how": "super ile ust cagir", "code": "class Dog < Animal; end"},
    "Kapsülleme": {"title": "Kapsulleme", "what": "@ + attr_* ile gizleme.", "how": "attr_reader :name", "code": "@name gizli kalir"},
    "Active Storage": {"title": "Active Storage", "what": "Dosya yukleme.", "how": "has_one_attached :image", "code": "file_field :image"},
    "before_action": {"title": "before_action", "what": "Controller callback.", "how": "Tekrar eden kodu toplar", "code": "before_action :set_post"},
    "form_with": {"title": "form_with", "what": "Rails form helper.", "how": "model: @post otomatik action", "code": "form_with model: @post"},
    "partial": {"title": "Partial", "what": "Tekrar eden view parcasi.", "how": "_form.html.erb, render 'form'", "code": "render 'form'"},
    "normalizes": {"title": "normalizes", "what": "Kaydetmeden veri duzenler.", "how": "strip, downcase", "code": "normalizes :email, with: ->(e) { e.strip }"},
    "FriendlyId": {"title": "FriendlyId", "what": "Slug URL.", "how": "/posts/baslik-slug", "code": "friendly_id :title"},
    "HTTP Metotları": {"title": "HTTP Metotlari", "what": "GET oku, POST olustur, PATCH guncelle, DELETE sil.", "how": "RESTful routes", "code": "GET /posts"},
    "Bootstrap Grid": {"title": "Bootstrap Grid", "what": "12 sutun responsive.", "how": "container, row, col-md-6", "code": '<div class="col-md-6">'},
}

ALL_GLOSSARY = {**INTPROG_GLOSSARY, **OOP_GLOSSARY}
