# -*- coding: utf-8 -*-
"""Haftalik calisma yollari — sifirdan baslayanlar icin adim adim rehber."""

INTPROG_WEEKLY_PATH = [
    {
        "week": 2,
        "sid": "hafta-2-ruby-rails-giris",
        "title": "Ruby & Rails Giris",
        "time": "2-3 saat",
        "goal": "Ruby dil mantigini ve MVC yapisini anla; proje nasil calisir ogren.",
        "steps": [
            {"text": "Basit Anlatim kutusunu bastan sona oku", "link": "#hafta-2-ruby-rails-giris"},
            {"text": "Ruby Temelleri panelini ac (Integer, String, Symbol)", "link": "#hafta-2-ruby-rails-giris"},
            {"text": "MVC akisini ciz: routes → controller → model → view", "link": "#hafta-2-ruby-rails-giris"},
            {"text": "Rails dizin yapisini incele (app/, config/, db/)", "link": "#hafta-2-ruby-rails-giris"},
            {"text": "Varsa hafta videosunu izle", "link": "#hafta-2-ruby-rails-giris"},
        ],
        "remember": ["Ruby'de her sey nesnedir", "rails s ile sunucu baslar", "MVC = veri + mantik + arayuz"],
    },
    {
        "week": 3,
        "sid": "hafta-3-orm-active-record",
        "title": "ORM & Active Record",
        "time": "2-3 saat",
        "goal": "SQL yazmadan veritabani islemi yap; find, find_by, where farkini bil.",
        "steps": [
            {"text": "Basit Anlatim: ORM = tablo ↔ Ruby sinifi", "link": "#hafta-3-orm-active-record"},
            {"text": "find vs find_by vs where tablosunu ezberle", "link": "#hafta-3-orm-active-record"},
            {"text": "Migration panelini oku; db:migrate ne yapar?", "link": "#hafta-3-orm-active-record"},
            {"text": "Komut referansindan db:* komutlarina bak", "link": "#komut-hizli-referans"},
        ],
        "remember": ["find bulamazsa HATA verir", "find_by nil doner", "where liste doner"],
    },
    {
        "week": 4,
        "sid": "hafta-4-enum-routes-controllers",
        "title": "Enum, Routes & Controllers",
        "time": "2-3 saat",
        "goal": "HTTP metotlarini ve 7 CRUD route'unu ogren.",
        "steps": [
            {"text": "GET/POST/PUT/PATCH/DELETE ne zaman kullanilir?", "link": "#hafta-4-enum-routes-controllers"},
            {"text": "resources :posts = 7 route mantigini anla", "link": "#hafta-4-enum-routes-controllers"},
            {"text": "Enum panelini oku (draft: 0 ne demek?)", "link": "#hafta-4-enum-routes-controllers"},
            {"text": "posts_path vs posts_url farkini not al", "link": "#hafta-4-enum-routes-controllers"},
        ],
        "remember": ["GET okur, POST olusturur, DELETE siler", "Enum: DB'de sayi, kodda isim"],
    },
    {
        "week": 5,
        "sid": "hafta-5-form-helpers-strong-parameters",
        "title": "Form & Strong Parameters",
        "time": "2 saat",
        "goal": "Form ile veri al; guvenli kaydetme mantigini anla.",
        "steps": [
            {"text": "form_with model: @post ornegini incele", "link": "#hafta-5-form-helpers-strong-parameters"},
            {"text": "Strong Parameters (post_params) panelini oku", "link": "#hafta-5-form-helpers-strong-parameters"},
            {"text": "Partial (_form) ve before_action mantigi", "link": "#hafta-5-form-helpers-strong-parameters"},
        ],
        "remember": ["Strong Params mass assignment saldirisini onler", "Partial _ ile baslar"],
    },
    {
        "week": 6,
        "sid": "hafta-6-bootstrap-frontend",
        "title": "Bootstrap Frontend",
        "time": "2 saat",
        "goal": "12 sutun grid ve navbar/footer yapısını ogren.",
        "steps": [
            {"text": "Grid sistemi: col-md-6 = yarim genislik", "link": "#hafta-6-bootstrap-frontend"},
            {"text": "container vs container-fluid farki", "link": "#hafta-6-bootstrap-frontend"},
            {"text": "Navbar ve footer partial orneklerini incele", "link": "#hafta-6-bootstrap-frontend"},
        ],
        "remember": ["Grid 12 sutun", "card ve btn siniflari hazir stil verir"],
    },
    {
        "week": 7,
        "sid": "hafta-7-model-iliskileri-kategori",
        "title": "Model Iliskileri",
        "time": "2-3 saat",
        "goal": "belongs_to / has_many / HABTM iliskilerini ayirt et.",
        "steps": [
            {"text": "belongs_to: FK bu tabloda — has_many: karsi taraf cok", "link": "#hafta-7-model-iliskileri-kategori"},
            {"text": "HABTM ara tablo mantigini oku", "link": "#hafta-7-model-iliskileri-kategori"},
            {"text": "scaffold ile hizli CRUD nasil olusur?", "link": "#hafta-7-model-iliskileri-kategori"},
        ],
        "remember": ["FK hangi tabloda belongs_to orada", "HABTM: id yok, iki FK var"],
    },
    {
        "week": 8,
        "sid": "hafta-8-validation-active-storage",
        "title": "Validation & Active Storage",
        "time": "2 saat",
        "goal": "Model dogrulama kurallari ve dosya yukleme.",
        "steps": [
            {"text": "validates presence, uniqueness, length ornekleri", "link": "#hafta-8-validation-active-storage"},
            {"text": "normalizes ne zaman kullanilir?", "link": "#hafta-8-validation-active-storage"},
            {"text": "has_one_attached :image mantigi", "link": "#hafta-8-validation-active-storage"},
        ],
        "remember": ["validates gecersizse kaydetmez", "normalizes kaydetmeden duzenler"],
    },
    {
        "week": 9,
        "sid": "hafta-9-i18n-friendlyid-action-text",
        "title": "I18n, FriendlyId & Action Text",
        "time": "2 saat",
        "goal": "Coklu dil, SEO URL ve zengin metin editoru.",
        "steps": [
            {"text": "I18n.t ve locale= parametresi", "link": "#hafta-9-i18n-friendlyid-action-text"},
            {"text": "FriendlyId slug URL mantigi", "link": "#hafta-9-i18n-friendlyid-action-text"},
            {"text": "Action Text zengin metin editoru", "link": "#hafta-9-i18n-friendlyid-action-text"},
        ],
        "remember": ["I18n.t metin cevirir", "FriendlyId /posts/1 yerine slug"],
    },
    {
        "week": 10,
        "sid": "hafta-10-devise-authorization",
        "title": "Devise & Authorization",
        "time": "2-3 saat",
        "goal": "Kullanici girisi ve rol bazli yetkilendirme.",
        "steps": [
            {"text": "Devise kurulum ve temel akis", "link": "#hafta-10-devise-authorization"},
            {"text": "Authentication vs Authorization farki", "link": "#hafta-10-devise-authorization"},
            {"text": "authenticate_user! ve current_user kullanimi", "link": "#hafta-10-devise-authorization"},
            {"text": "Ezber listesini oku", "link": "#sinav-ezber-listesi"},
            {"text": "Quiz ile kendini test et", "link": "#sinav-sorulari-kendini-test-et"},
        ],
        "remember": ["Authentication = kimlik", "Authorization = yetki", "current_user giris yapan"],
    },
]

OOP_WEEKLY_PATH = [
    {
        "week": 1,
        "sid": "hafta-1-oop-giris-prosedurel-programlama",
        "title": "OOP Giris & Prosedurel Programlama",
        "time": "2 saat",
        "goal": "Prosedurel ile OOP farkini anla; Python'da class mantigina gir.",
        "steps": [
            {"text": "Basit Anlatim: prosedurel vs OOP", "link": "#hafta-1-oop-giris-prosedurel-programlama"},
            {"text": "OOP tarihi ve temel prensipler paneli", "link": "#hafta-1-oop-giris-prosedurel-programlama"},
            {"text": "Konu indeksinden OOP terimlerine bak", "link": "#oop-konu-indeksi"},
        ],
        "remember": ["Prosedurel = fonksiyon + global veri", "OOP = nesne (veri + davranis)"],
    },
    {
        "week": 2,
        "sid": "hafta-2-siniflar-nesneler",
        "title": "Siniflar & Nesneler",
        "time": "2-3 saat",
        "goal": "class, __init__, self ve instance variable kavramlari.",
        "steps": [
            {"text": "class tanimi ve nesne olusturma ornekleri", "link": "#hafta-2-siniflar-nesneler"},
            {"text": "__init__ ve self ne ise yarar?", "link": "#hafta-2-siniflar-nesneler"},
            {"text": "Instance metot orneklerini kodla", "link": "#hafta-2-siniflar-nesneler"},
        ],
        "remember": ["class = kalip, nesne = ornek", "self = bu nesne"],
    },
    {
        "week": 3,
        "sid": "hafta-3-kapsulleme",
        "title": "Kapsulleme (Encapsulation)",
        "time": "2 saat",
        "goal": "Veriyi gizleme, getter/setter, @property.",
        "steps": [
            {"text": "_ ve __ ile gizleme convention", "link": "#hafta-3-kapsulleme"},
            {"text": "@property ile kontrollu erisim", "link": "#hafta-3-kapsulleme"},
            {"text": "Kapsulleme neden gerekli? panelini oku", "link": "#hafta-3-kapsulleme"},
        ],
        "remember": ["Encapsulation = guvenli veri", "@property getter/setter saglar"],
    },
    {
        "week": 4,
        "sid": "hafta-4-kalitim-miras",
        "title": "Kalitim (Inheritance)",
        "time": "2-3 saat",
        "goal": "class Child(Parent), override ve super().",
        "steps": [
            {"text": "Kalitim syntax: class Cocuk(Ebeveyn)", "link": "#hafta-4-kalitim-miras"},
            {"text": "Method overriding ornekleri", "link": "#hafta-4-kalitim-miras"},
            {"text": "isinstance ve type kontrolu", "link": "#hafta-4-kalitim-miras"},
        ],
        "remember": ["Kalitim kod tekrarini azaltir", "super() ust sinifi cagirir"],
    },
    {
        "week": 5,
        "sid": "hafta-5-super-coklu-miras-statik-metot",
        "title": "super, Coklu Miras & @staticmethod",
        "time": "2-3 saat",
        "goal": "MRO sirasi ve staticmethod farki.",
        "steps": [
            {"text": "super().__init__() kullanimi", "link": "#hafta-5-super-coklu-miras-statik-metot"},
            {"text": "Coklu miras ve MRO mantigi", "link": "#hafta-5-super-coklu-miras-statik-metot"},
            {"text": "@staticmethod vs instance metot", "link": "#hafta-5-super-coklu-miras-statik-metot"},
        ],
        "remember": ["MRO = metot arama sirasi", "@staticmethod nesne gerektirmez"],
    },
    {
        "week": 6,
        "sid": "hafta-6-polimorfizm-soyut-sinif",
        "title": "Polimorfizm & Soyut Sinif",
        "time": "2-3 saat",
        "goal": "Polimorfizm, duck typing, ABC.",
        "steps": [
            {"text": "Ayni metod farkli davranis ornekleri", "link": "#hafta-6-polimorfizm-soyut-sinif"},
            {"text": "ABC ve @abstractmethod", "link": "#hafta-6-polimorfizm-soyut-sinif"},
            {"text": "Duck typing ne demek?", "link": "#hafta-6-polimorfizm-soyut-sinif"},
        ],
        "remember": ["ABC'den dogrudan nesne olusturulmaz", "Duck typing = ne yaptigina bak"],
    },
    {
        "week": 7,
        "sid": "hafta-7-tasarim-desenleri-giris",
        "title": "Tasarim Desenleri — Giris",
        "time": "2 saat",
        "goal": "Singleton, Factory gibi temel desenler.",
        "steps": [
            {"text": "Tasarim deseni nedir? panelini oku", "link": "#hafta-7-tasarim-desenleri-giris"},
            {"text": "Singleton ornegini incele", "link": "#hafta-7-tasarim-desenleri-giris"},
            {"text": "Factory pattern mantigi", "link": "#hafta-7-tasarim-desenleri-giris"},
        ],
        "remember": ["Desen = tekrar eden cozum sablonu", "Singleton tek nesne uretir"],
    },
    {
        "week": 8,
        "sid": "hafta-8-tasarim-desenleri-devam",
        "title": "Tasarim Desenleri — Devam",
        "time": "2 saat",
        "goal": "Observer, Decorator desenleri.",
        "steps": [
            {"text": "Observer deseni ornegi", "link": "#hafta-8-tasarim-desenleri-devam"},
            {"text": "Decorator deseni ornegi", "link": "#hafta-8-tasarim-desenleri-devam"},
            {"text": "Desenler SOLID ile nasil uyumlu?", "link": "#hafta-8-tasarim-desenleri-devam"},
        ],
        "remember": ["Observer olay dinler", "Decorator davranis ekler"],
    },
    {
        "week": 9,
        "sid": "hafta-9-solid-prensipleri",
        "title": "SOLID Prensipleri (PDF)",
        "time": "2-3 saat",
        "goal": "SRP, OCP, LSP, ISP, DIP tanimlarini ogren.",
        "steps": [
            {"text": "Her SOLID harfi icin tanim panelini oku", "link": "#hafta-9-solid-prensipleri"},
            {"text": "Kotu vs iyi kod orneklerini karsilastir", "link": "#hafta-9-solid-prensipleri"},
            {"text": "OOP ezber listesinden SOLID maddelerine bak", "link": "#oop-ezber"},
        ],
        "remember": ["SRP tek is", "OCP genislet kapama", "LSP yerine koy", "ISP kucuk arayuz", "DIP soyuta bagimli ol"],
    },
    {
        "week": 10,
        "sid": "hafta-10-solid-calisma-odev-cozumleri",
        "title": "SOLID Calisma & Odev Cozumleri",
        "time": "3-4 saat",
        "goal": "Odev formatinda SOLID; sinif arkadas ornekleri ve PDF alistirmalari.",
        "steps": [
            {"text": "5 SOLID ilkesi odev formatinda calis", "link": "#hafta-10-solid-calisma-odev-cozumleri"},
            {"text": "Sinif arkadas orneklerini incele (SRP→DIP)", "link": "#hafta-10-solid-calisma-odev-cozumleri"},
            {"text": "PDF alistirmalari cozumlerini oku", "link": "#hafta-10-solid-calisma-odev-cozumleri"},
            {"text": "LSP Solo Leveling ornegini calis", "link": "#hafta-10-solid-calisma-odev-cozumleri"},
        ],
        "remember": ["Her ilke: tanim + amac + kotu/iyi kod", "Sinavda LSP ornegi cikabilir"],
    },
]
